apiVersion: 1

datasources:
  - name: ClickHouse
    uid: apexio_clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: apexio
      username: default
    secureJsonData:
      password: ""
