#deployment and service for grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_SERVER_HTTP_PORT
              value: "3000"
            - name: GF_DATASOURCES_DEFAULT.elasticsearch.url
              value: "http://elasticsearch-service"
            - name: GF_DATASOURCES_DEFAULT.elasticsearch.index
              value: "raw_logs"
            - name: GF_DATASOURCES_DEFAULT.elasticsearch.user 
              valueFrom: 
                secretKeyRef:
                  name: elasticsearch-secret
                  key: USER
            - name: GF_DATASOURCES_DEFAULT.elasticsearch.password
              valueFrom: 
                secretKeyRef: 
                  name: elasticsearch-secret
                  key: PASSWORD



---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000 #port exposed within the cluster
      targetPort: 3000 #port in the container
      nodePort: 30000





