#deployment and service file for our log processing service 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log_processing_service-deployment
  labels:
    app: log_processing_service 
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: log_processing_service
  template:
    metadata:
      labels:
        app: log_processing_service
    spec:
      containers:
        - name: log_processing_service
          image: log_processing_service:1.0
          ports:
            - containerPort: 3003
---

apiVersion: v1
kind: Service
metadata:
  name: log_processing_service-service
spec: 
  type: NodePort
  selector: 
    app: log_processing_service 
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30030
