#deployment and service for sourceweb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-web-deployment 
  labels:
    app: source-web 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-web  
  template:
    metadata:
      labels:
        app: source-web 
    spec:
      containers:
        - name: source-web 
          image: source_web:1.0
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: source-web-service
spec:
  type: NodePort
  selector:
    app: source-web 
  ports:
    - protocol: TCP
      port: 3001 # port exposed within the cluster
      targetPort: 3001 #the port in the go app containers 
      nodePort: 30010 #for external access
